### ISSUE TITLE
`TransportConfigurer` is only set when dtsync publisher is instantiated from existing data transfer

### ISSUE THREAD

**Issue by masih** [filecoin-project/go-legs#108]
See [here](https://github.com/filecoin-project/go-legs/blob/main/dtsync/util.go#L37-L38). Why?

**Comment by gammazero** [comment]
When we create our own datateransfer we also create our own graphsync implementation [here](
https://github.com/filecoin-project/go-legs/blob/main/dtsync/util.go#L80) and give it the linksystem.

In the case where there is an existing graphsync, we need to give it the linksystem that legs is using.
