### ISSUE TITLE
Remove topic from head publisher protocol ID

### ISSUE THREAD

**Issue by masih** [filecoin-project/go-legs#69]
The head publisher protocol ID includes [the topic](https://github.com/filecoin-project/go-legs/blob/main/p2p/protocol/head/head.go#L39) on which update roots are published. Subsystems like `storetheindex` using legs protocol take topic as a configuration value. 

It would be great if that topic is either removed from protocol ID of head publisher or is different from the gossipsub topic name so that users of legs can fix that to some static string. 

This change will also simplify the syncer API, when dynamically fetching head.

**Comment by willscott** [comment]
i think we want different head protocols for different networks.
That said, i think there's a pretty reasonable heuristic that can be used to guess what an appropriate protocol is to ask for the head.

**Comment by masih** [comment]
> i think we want different head protocols for different networks.

Would that not be an implicit thing identified by the endpoint we are calling? 

And If we definitely need to expose it in head publisher, would it make sense to have an endpoint that returns the topic rather than adding the topic to protocol ID?

**Comment by willscott** [comment]
what do you mean by endpoint? it won't be guaranteed to be unique to a single libp2p peer / multiaddr if that's what you mean.
E.g. you could imagine dealbots running an instance of legs where they provide data for pando, and a different instance providing a different retrieval info for a different subsystem/network.

I thin in prod systems we should have a topic / id that's explicitly specified on both sides.

For validation, the common case is likely that most libp2p peers have a single legs protocol. Enumerating them and finding the one with `/legs` should be a pretty reasonable heuristic to provide a default when only one is present

**Comment by masih** [comment]
"libp2p peer / multiaddr" is what I meant by endpoint. OK I see; that makes sense.

Alternatives I thought of were query parameters, where `/legs/head` is always singular but takes a `?topic` parameter when more than one "legs" instance is running on that host. Or simply return a json mapping of topic to head as response. 

But even then we still need to include topic somewhere.

Changing the `QueryHead` to detect topic sounds good when given topic is empty

**Comment by MarcoPolo** [comment]
Alternate suggestion:

Keep the topic as part of the protocol id (as is).

In storetheindex (which is the use case this issue sprang from) we add an option to manually sync a specific publisher on a specific topic.

I don't think it's a good idea to have an implied default head responder (omitting the topic). A simple example, what happens if a publishers has two topics and shuts one of them down. A subscriber will have no idea which head is for which topic.

**Comment by masih** [comment]
Yup Discussed in colo; closing. Thank you all
