### ISSUE TITLE
Exchange retries in subscriber

### ISSUE THREAD

**Issue by adlrocha** [filecoin-project/go-legs#9]
Consider [retrying the exchange](https://github.com/willscott/go-legs/blob/b81c14e0951bd5fd8f470a336136f9b737403825/subscribe.go#L205) at least once if there is an error in the data channel. Errors related to state machine migrations may be overcome restarting the data channel.

**Comment by gammazero** [comment]
@hannahhoward Is this still something that should be done, given recent upgrades to graphsync?

**Comment by hannahhoward** [comment]
"Errors related to state machine migrations" -- if we are seeing this, we're not properly waiting for migrations to complete before accepting requests. I think this has been resolved for some time in prod but not sure. These would not be affected by recent changes, which have currently been reverted.

**Comment by gammazero** [comment]
I believe this may have been fixed, and even if not, I am closing this issue as we need a more specific failure case to address.
