### ISSUE TITLE
legs subscriber must allow datatrasfer to be optionally set

### ISSUE THREAD

**Issue by masih** [filecoin-project/go-legs#95]
Otherwise, a lib2p host with go-legs subscriber cannot start a graphsync server, since registration of stream handler for graphsync server is singular.

It seems limiting to require users of go-legs to not start up a graphsync server if they are running a go-legs subscriber.

Consider adding the option back which was removed [here](https://github.com/filecoin-project/go-legs/pull/89/files#diff-086a37ef11c8fd9a2516991339db79c207741ac98dd89c8215d31a8bead2814fL64-L71).

Consider alternative approaches to guaranteeing the correctness of blockhook mechanism.

**Comment by masih** [comment]
Changing that option to take both `datatransfer.Manager` and `graphsync.GraphExchange` should be sufficient to allow both registration of block hook at root and instantiate if not set.

**Comment by willscott** [comment]
or we can add it back on just on the publisher side, right?

**Comment by masih** [comment]
It was never removed from the publisher side.

**Comment by MarcoPolo** [comment]
Done in #96
